export const INDEX_GET = 'INDEX_GET';
export const TEXT_CHANGE = 'TEXT_CHANGE';
/* 首页 */
export const ROUTER_INTO_PERIPHERAL = 'ROUTER_INTO_PERIPHERAL';
export const ROUTER_LEAVE_PERIPHERAL = 'ROUTER_LEAVE_PERIPHERAL';

/* headLines页面  */
export const HEADLINES_NEWS_GET = 'HEADLINES_NEWS_GET';
export const HEADLINES_NEWS_GET_MORE = 'HEADLINES_NEWS_GET_MORE';